version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
